parameters:
  agent_pool: "" # vs2017-win2016 (Linux not support in some task)
  azure_dev_ops_project_id: "" # 7b4fddf7-fb53-4b12-bfcb-f87ad3774a32 (The project GUID from which to download the pipeline artifacts)
  azure_dev_ops_build_definition_id: "" # 717 (The definition ID of the build pipeline)
  subscription: "" # AI Infra Build (00c06639-6ee4-454e-8058-8d8b1703bd87)
  storage: "" # featurizersbuild (The name of storage account in Azure)
  containerName: "" # Archive (The name of the container to which the files will be copied)

stages:
  - stage: AzureUpload_Stage
    displayName: "Upload to Azure"
    dependsOn: [] # No dependencies

    jobs:
      - job: AzureUpload_Job
        timeoutInMinutes: 240

        displayName: "Upload"

        pool:
          name: Azure Pipelines
          demands: azureps
          vmImage: "${{ parameters.agent_pool }}"

        steps:
          - template: PublishInitialize.steps_template.yaml
            parameters:
              azure_dev_ops_project_id: ${{ parameters.azure_dev_ops_project_id }}
              azure_dev_ops_build_definition_id: ${{ parameters.azure_dev_ops_build_definition_id }}

          - task: CopyFiles@2
            displayName: Copying Documentation
            inputs:
              SourceFolder: "$(Pipeline.Workspace)/Documentation"
              Contents: "**"
              TargetFolder: "$(Pipeline.Workspace)/upload/$(Build.TriggeredBy.BuildNumber)/Documentation/"

          - task: CopyFiles@2
            displayName: Copying Packages
            inputs:
              SourceFolder: "$(Pipeline.Workspace)/Package"
              Contents: "**"
              TargetFolder: "$(Pipeline.Workspace)/upload/$(Build.TriggeredBy.BuildNumber)/Package/"

          - task: PythonScript@0
            displayName: "Trim Directory Name"
            inputs:
              scriptSource: inline
              script: |
                import os
                import sys

                basedir = sys.argv[1]
                for fn in os.listdir(basedir):
                  if not os.path.isdir(os.path.join(basedir, fn)):
                    continue # Not a directory
                  if fn == "{}(Build.TriggeredBy.BuildNumber)".format("$"):
                    os.rename(os.path.join(basedir, fn), os.path.join(basedir, 'Independent Publish_' + sys.argv[2]))
                  else:
                    os.rename(os.path.join(basedir, fn), os.path.join(basedir, fn[-13:]))
              arguments: '$(Pipeline.Workspace)\upload $(buildId)'

          - task: AzureFileCopy@2
            displayName: "AzureBlob File Copy"
            inputs:
              SourcePath: "$(Pipeline.Workspace)/upload"
              azureSubscription: "${{ parameters.subscription }}"
              Destination: "AzureBlob"
              storage: "${{ parameters.storage }}"
              ContainerName: "${{ parameters.containerName }}"
