# This template is necessary because we can't create a job with an empty container string. Therefore,
# the container attribute is only present when there is a container provided.

parameters:
  operating_system: "" # Windows|Linux

  configuration: ""
  agent_pool: ""
  agent_pool_container: ""
  steps: ""

jobs:
  - ${{ if not(eq(parameters.agent_pool_container, '')) }}:
      - job: BuildAndTest_${{ parameters.operating_system }}_${{ parameters.configuration}}_${{ parameters.agent_pool_container }}_Job

        # In the UX, this display name contains redundant info (the OS and config appear twice). However, it
        # needs to be here to ensure that the information appears in the status email messages.
        displayName: "Build and Test (${{ parameters.operating_system }} - ${{ parameters.configuration }})"
        pool:
          vmImage: "${{ parameters.agent_pool }}"
        container: "${{ parameters.agent_pool_container }}"

        workspace:
          clean: all

        steps: ${{ parameters.steps }}

  - ${{ if eq(parameters.agent_pool_container, '') }}:
      - job: BuildAndTest_${{ parameters.operating_system }}_${{ parameters.configuration}}_Job

        # In the UX, this display name contains redundant info (the OS and config appear twice). However, it
        # needs to be here to ensure that the information appears in the status email messages.
        displayName: "Build and Test (${{ parameters.operating_system }} - ${{ parameters.configuration }})"
        pool:
          vmImage: "${{ parameters.agent_pool }}"

        workspace:
          clean: all

        steps: ${{ parameters.steps }}
