name: $(TeamProject)-$(BuildDefinitionName)-$(SourceBranchName)-$(Date:yyyy.MM.dd)-$(Rev:rr)

trigger:
  batch: true
  branches:
    include:
      - master

resources:
  containers:
    - container: universal_linux
      image: universal_linux
      endpoint: featurizersbuild

# Note that a variable set in this file will always override a value set within the editor.
# Therefore, do not set the default value to False here but instead do it in an initialization
# script.
#
#   variables:
#     release_build: False                  # Set to true to create a release build
#     prerelease_build_name: ""             # Set to a value (e.g. "preview.1" to create a preview build)

stages:
  - template: Prerequisites.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      release_build: $(release_build)
      prerelease_build_name: $(prerelease_build_name)

  # Windows/clang/x64 [Official Build]
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x64
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: True
      esrp_connected_service_name: "ESRP CodeSigning Connection"

  # Windows/clang/x86 [Official Build]
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x86
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False
      esrp_connected_service_name: "ESRP CodeSigning Connection"

  # TODO: # Linux/GCC/universal_linux [Official Build]
  # TODO: - template: BuildAndTest.stage_template.yaml
  # TODO:   parameters:
  # TODO:     agent_pool: ubuntu-16.04
  # TODO:     agent_pool_container: universal_linux
  # TODO:     operating_system: Linux
  # TODO:     configuration: universal_linux
  # TODO:     dependencies:
  # TODO:       - Prerequisites_Stage
  # TODO:     enable_code_coverage: False
  # TODO:     esrp_connected_service_name: "ESRP CodeSigning Connection"

  # MacOS/clang/x64
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: macOS-10.14
      operating_system: MacOS
      configuration: system_compiler
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False
      esrp_connected_service_name: "ESRP CodeSigning Connection"

  # Windows/MSVC/x64
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x64_MSVC
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False
      # Note that this build doesn't produce "official" binaries and is here for a santity check only. Therefore, no code signing.

  # Windows/MSVC/x86
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x86_MSVC
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False
      # Note that this build doesn't produce "official" binaries and is here for a santity check only. Therefore, no code signing.

  # Linux/clang/x64
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: ubuntu-16.04
      operating_system: Linux
      configuration: x64
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False
      # Note that this build doesn't produce "official" binaries and is here for a santity check only. Therefore, no code signing.

  # Linux/GCC/system_compiler
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: ubuntu-16.04
      operating_system: Linux
      configuration: system_compiler
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False
      # Note that this build doesn't produce "official" binaries and is here for a santity check only. Therefore, no code signing.

  - template: Documentation.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: system_compiler
      dependencies:
        - BuildAndTest_Windows_x64_Stage
        - BuildAndTest_Windows_x86_Stage
        # TODO: - BuildAndTest_Linux_universal_linux_Stage
        - BuildAndTest_MacOS_system_compiler_Stage
        - BuildAndTest_Windows_x64_MSVC_Stage
        - BuildAndTest_Windows_x86_MSVC_Stage
        - BuildAndTest_Linux_x64_Stage
        - BuildAndTest_Linux_system_compiler_Stage

  - template: Package.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: system_compiler
      esrp_connected_service_name: "ESRP CodeSigning Connection"

      dependencies:
        - BuildAndTest_Windows_x64_Stage
        - BuildAndTest_Windows_x86_Stage
        # TODO: - BuildAndTest_Linux_universal_linux_Stage
        - BuildAndTest_MacOS_system_compiler_Stage
        - BuildAndTest_Windows_x64_MSVC_Stage
        - BuildAndTest_Windows_x86_MSVC_Stage
        - BuildAndTest_Linux_x64_Stage
        - BuildAndTest_Linux_system_compiler_Stage
