parameters:
  operating_system: "" # Windows|Linux|MacOS
  esrp_connected_service_name: "None" # <Name>|None

  dependencies: []
  configuration: ""
  agent_pool: ""

  # These are parameters not because they will be configued by the caller, but rather because arrays can be
  # defined here and not in variables.
  build_configurations:
    - Debug
    - Release

stages:
  - stage: Package_${{ parameters.operating_system }}_${{ parameters.configuration }}_Stage
    displayName: "Package Stage"
    dependsOn: ${{ parameters.dependencies }}

    jobs:
      - job: Package_${{ parameters.operating_system }}_${{ parameters.configuration }}_Job

        # In the UX, this display name contains redundant info (the OS and config appear twice). However, it
        # needs to be here to ensure that the information appears in the status email messages.
        displayName: "Package Job"
        pool:
          vmImage: "${{ parameters.agent_pool }}"
        workspace:
          clean: all

        steps:
          - template: Initialize.steps_template.yaml
            parameters:
              operating_system: ${{ parameters.operating_system }}
              enable_code_coverage: False

          - script: |-
              echo "esrp_connected_service_name- ${{ parameters.esrp_connected_service_name }}"
              echo "dependencies - ${{ join(', ', parameters.dependencies) }}"
              echo "configuration - ${{ parameters.configuration }}"
              echo "agent_pool - ${{ parameters.agent_pool }}
            displayName: "[DEBUG] Display Package Variables"

          - script: |-
              $(azure_display_all_environment_vars)
            displayName: "[DEBUG] Environment Variables (Before Activation)"

          - script: |-
              $(azure_bootstrap_command) $(azure_agent_temp_directory) "/required_ancestor_dir=$(azure_agent_temp_directory)" "/configuration=${{ parameters.configuration }}" /use_ascii /verbose
            displayName: "<Bootstrap>"
            timeoutInMinutes: 180

          - script: |-
              $(azure_activate_script) ${{ parameters.configuration }} && $(azure_display_all_environment_vars)
            displayName: "[DEBUG] Environment Variables (After Activation)"

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: "Windows - x64"
              targetPath: "$(Build.StagingDirectory)/Windows - x64"
            displayName: 'Download "Windows - x64" Artifacts'
            timeoutInMinutes: 180

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: "Windows - x86"
              targetPath: "$(Build.StagingDirectory)/Windows - x86"
            displayName: 'Download "Windows - x86" Artifacts'
            timeoutInMinutes: 180

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              # TODO: artifactName: "Linux - universal_linux"
              artifactName: "Linux - system_compiler"
              targetPath: "$(Build.StagingDirectory)/Linux - universal_linux"
            displayName: 'Download "Linux - universal_linux" Artifacts'
            timeoutInMinutes: 180

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: current
              artifactName: "MacOS - system_compiler"
              targetPath: "$(Build.StagingDirectory)/MacOS - system_compiler"
            displayName: 'Download "MacOS - system_compiler" Artifacts'
            timeoutInMinutes: 180

          - ${{ each build_configuration in parameters.build_configurations }}:
              - script: |-
                  $(azure_activate_script) ${{ parameters.configuration }} && python src/FeaturizerPrep/SharedLibrary/Build.py Package "$(azure_artifacts_directory)/Artifacts/Packages/${{ build_configuration }}" "/build_dir=$(Build.StagingDirectory)/Windows - x64/Builder/${{ build_configuration }}" "/build_dir=$(Build.StagingDirectory)/Windows - x86/Builder/${{ build_configuration }}" "/build_dir=$(Build.StagingDirectory)/Linux - universal_linux/Builder/${{ build_configuration }}" "/build_dir=$(Build.StagingDirectory)/MacOS - system_compiler/Builder/${{ build_configuration }}" /verbose
                displayName: "<Build.py Package - ${{ build_configuration }}>"
                timeoutInMinutes: 180

          # Sign the packages
          - ${{ if not(eq(parameters.esrp_connected_service_name, 'None')) }}:
              - task: CopyFiles@2
                displayName: "Copy Files to Sign"
                inputs:
                  SourceFolder: "$(azure_artifacts_directory)/Artifacts/Packages"
                  TargetFolder: "$(azure_artifacts_directory)/Artifacts/Packages.original"
                  CleanTargetFolder: true

              - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
                displayName: "ESRP CodeSign"
                inputs:
                  ConnectedServiceName: ${{ parameters.esrp_connected_service_name }}
                  FolderPath: "$(azure_artifacts_directory)/Artifacts/Packages"
                  Pattern: "*.nupkg"
                  signConfigType: inlineSignParams
                  inlineOperation: |-
                    [
                        {
                            "KeyCode" : "CP-401405",
                            "OperationCode" : "NuGetSign",
                            "Parameters" : {},
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        },
                        {
                            "KeyCode" : "CP-401405",
                            "OperationCode" : "NuGetVerify",
                            "Parameters" : {},
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        }
                    ]

          - task: PublishPipelineArtifact@0
            displayName: "Publish Artifacts"
            inputs:
              targetPath: "$(azure_artifacts_directory)/Artifacts"
              artifactName: "Package"
            timeoutInMinutes: 180
