name: $(TeamProject)-$(BuildDefinitionName)-$(SourceBranchName)-$(Date:yyyy.MM.dd)-$(Rev:rr)

trigger: none

resources:
  containers:
    - container: universal_linux
      image: universal_linux
      endpoint: featurizersbuild

stages:
  - template: Prerequisites.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      release_build: False
      prerelease_build_name: ""

  # Windows/clang/x64 [Official build]
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x64
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: True

  # Windows/clang/x86 [Official build]
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x86
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False

  # TODO: # Linux/GCC/universal_linux [Official build]
  # TODO: - template: BuildAndTest.stage_template.yaml
  # TODO:   parameters:
  # TODO:     agent_pool: ubuntu-16.04
  # TODO:     agent_pool_container: universal_linux
  # TODO:     operating_system: Linux
  # TODO:     configuration: universal_linux
  # TODO:     dependencies:
  # TODO:       - Prerequisites_Stage
  # TODO:     enable_code_coverage: False

  # MacOS/clang/x64
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: macOS-10.14
      operating_system: MacOS
      configuration: system_compiler
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False

  # Windows/MSVC/x64
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x64_MSVC
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False

  # Windows/MSVC/x86
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: x86_MSVC
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False

  # Linux/clang/x64
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: ubuntu-16.04
      operating_system: Linux
      configuration: x64
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False

  # Linux/GCC/system_compiler
  - template: BuildAndTest.stage_template.yaml
    parameters:
      agent_pool: ubuntu-16.04
      operating_system: Linux
      configuration: system_compiler
      dependencies:
        - Prerequisites_Stage
      enable_code_coverage: False

  - template: Package.stage_template.yaml
    parameters:
      agent_pool: windows-2019
      operating_system: Windows
      configuration: system_compiler
      dependencies:
        - BuildAndTest_Windows_x64_Stage
        - BuildAndTest_Windows_x86_Stage
        # TODO: - BuildAndTest_Linux_universal_linux_Stage
        - BuildAndTest_MacOS_system_compiler_Stage
        - BuildAndTest_Windows_x64_MSVC_Stage
        - BuildAndTest_Windows_x86_MSVC_Stage
        - BuildAndTest_Linux_x64_Stage
        - BuildAndTest_Linux_system_compiler_Stage
