name: $(TeamProject)-$(BuildDefinitionName)-$(SourceBranchName)-$(Date:yyyy.MM.dd)-$(Rev:rr)

#TODO: Build completion triggers are not yet supported in YAML syntax
#reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#build-completion-triggers
trigger: none

# User will need to specify buildId if publishing with non-triggered build
stages:
    - template: AzureUpload.stage_template.yaml
      parameters:
          agent_pool: vs2017-win2016
          project: 7b4fddf7-fb53-4b12-bfcb-f87ad3774a32
          definition: 717
          subscription: AI Infra Build (00c06639-6ee4-454e-8058-8d8b1703bd87)
          storage: featurizersbuild
          containerName: Archive


